/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bwaa;

/**
 *
 * @author WINDOWS 10
 */
public class BiodataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form BiodataSiswa
     */
    public BiodataSiswa(String nama, String absen, String jurusan, String alamat) {
         String nm, abs, jur, almt;
    String kelas = combo.getSelectedItem().toString();
    nm = idnama.getText();
    abs = idabsen.getText();
    jur = idjurusan.getText();
    almt = idalamat.getText();
    //jurusan
    if(cbrpl.isSelected()){
        jur = "RPL";
    if(combo.getSelectedItem()== "XI RPL 1"){
    }
    if(combo.getSelectedItem()=="XI RPl 2"){
    }
      if(combo.getSelectedItem()=="XI RPl 3"){
          
      }
        if(combo.getSelectedItem()=="XI RPl 4"){
        }
    }else if(cbtkj.isSelected()){
        jur = "TKJ";
          if(combo.getSelectedItem()=="XI TKJ 1"){
    }
            if(combo.getSelectedItem()=="XI TKJ 2"){
    }
              if(combo.getSelectedItem()=="XI TKJ 3"){
              }
                if(combo.getSelectedItem()=="XI TKJ 4"){
            }
    }else{jur = "";
    new frame2(nm,abs,jur,almt.kelas).setVisible(true);
    }
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        idnama = new javax.swing.JLabel();
        idabsen = new javax.swing.JLabel();
        idkelas = new javax.swing.JLabel();
        idjurusan = new javax.swing.JLabel();
        idalamat = new javax.swing.JLabel();
        cbnama = new javax.swing.JTextField();
        cbabsen = new javax.swing.JTextField();
        cbrpl = new javax.swing.JRadioButton();
        cbtkj = new javax.swing.JRadioButton();
        cbalamat = new javax.swing.JTextField();
        idsubmit = new javax.swing.JButton();
        idexit = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel1.setText("Biodata Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(308, 37, 114, 38);

        idnama.setText("NAMA");
        getContentPane().add(idnama);
        idnama.setBounds(70, 120, 130, 16);

        idabsen.setText("ABSEN");
        getContentPane().add(idabsen);
        idabsen.setBounds(69, 175, 120, 16);

        idkelas.setText("KELAS");
        getContentPane().add(idkelas);
        idkelas.setBounds(69, 236, 90, 16);

        idjurusan.setText("JURUSAN");
        getContentPane().add(idjurusan);
        idjurusan.setBounds(69, 288, 80, 16);

        idalamat.setText("ALAMAT");
        getContentPane().add(idalamat);
        idalamat.setBounds(69, 353, 70, 16);
        getContentPane().add(cbnama);
        cbnama.setBounds(220, 120, 160, 22);

        cbabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbabsenActionPerformed(evt);
            }
        });
        getContentPane().add(cbabsen);
        cbabsen.setBounds(220, 170, 160, 22);

        cbrpl.setText("RPL");
        getContentPane().add(cbrpl);
        cbrpl.setBounds(180, 280, 49, 25);

        cbtkj.setText("TKJ");
        getContentPane().add(cbtkj);
        cbtkj.setBounds(270, 280, 49, 25);
        getContentPane().add(cbalamat);
        cbalamat.setBounds(190, 350, 160, 22);

        idsubmit.setText("SUBMIT");
        getContentPane().add(idsubmit);
        idsubmit.setBounds(620, 290, 77, 25);

        idexit.setText("EXIT");
        getContentPane().add(idexit);
        idexit.setBounds(620, 350, 70, 25);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XR1", "XR2", "XR3", "XR4", "XR5", "XR6", "XR7", "XT1", "XT2", "XT3", "XT4", "XT5", "XT6" }));
        getContentPane().add(combo);
        combo.setBounds(220, 230, 50, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbabsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbabsenActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cbabsen;
    private javax.swing.JTextField cbalamat;
    private javax.swing.JTextField cbnama;
    private javax.swing.JRadioButton cbrpl;
    private javax.swing.JRadioButton cbtkj;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel idabsen;
    private javax.swing.JLabel idalamat;
    private javax.swing.JButton idexit;
    private javax.swing.JLabel idjurusan;
    private javax.swing.JLabel idkelas;
    private javax.swing.JLabel idnama;
    private javax.swing.JButton idsubmit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
